Repository kimmandoo/Ping, pull requests merged in 2024-05, with the labels that each got.

#4 패키지 구조 정리
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ping/app/PingApplication.kt
  app/src/main/java/com/ping/app/data/repository/TestRepo.kt
  app/src/main/java/com/ping/app/data/repository/TestRepoImpl.kt
  app/src/main/java/com/ping/app/domain/model/Test.kt
  app/src/main/java/com/ping/app/domain/repository/TestRepo.kt
  app/src/main/java/com/ping/app/domain/usecase/TestUsecase.kt
  app/src/main/java/com/ping/app/presentation/ui/feature/map/MapViewModel.kt
  app/src/main/java/com/ping/app/presentation/util/Constants.kt
  app/src/main/java/com/ping/app/presentation/util/FunctionUtil.kt
  app/src/main/java/com/ping/app/ui/base/BaseBottomSheetDialogFragment.kt
  app/src/main/java/com/ping/app/ui/base/BaseFragment.kt
  app/src/main/java/com/ping/app/ui/container/MainActivity.kt
  app/src/main/java/com/ping/app/ui/feature/login/LoginFragment.kt
  app/src/main/java/com/ping/app/ui/feature/main/MainFragment.kt
  app/src/main/java/com/ping/app/ui/feature/main/MainViewModel.kt
  app/src/main/java/com/ping/app/ui/feature/map/PingAddMapFragment.kt
  app/src/main/java/com/ping/app/ui/feature/map/PingAddPostFragment.kt
  app/src/main/java/com/ping/app/ui/feature/map/PingMapFragment.kt
  app/src/main/java/com/ping/app/ui/feature/map/PingMapViewModel.kt
  app/src/main/java/com/ping/app/ui/util/Constants.kt
  app/src/main/java/com/ping/app/ui/util/FunctionUtil.kt
  app/src/main/java/com/ping/app/ui/util/LocationHelper.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_main.xml
  app/src/main/res/layout/fragment_ping_add_post.xml
  app/src/main/res/layout/fragment_ping_map.xml
  app/src/main/res/layout/fragment_ping_map_add.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: REFACTOR

#5 Feature/#2 navermap add ping
  app/src/main/java/com/ping/app/PingApplication.kt
  app/src/main/java/com/ping/app/data/repository/PingMapRepoImpl.kt
  app/src/main/java/com/ping/app/data/repository/TestRepoImpl.kt
  app/src/main/java/com/ping/app/domain/dao/PingMapRepo.kt
  app/src/main/java/com/ping/app/domain/dao/TestRepo.kt
  app/src/main/java/com/ping/app/domain/model/Gathering.kt
  app/src/main/java/com/ping/app/ui/feature/map/PingAddMapFragment.kt
  app/src/main/java/com/ping/app/ui/feature/map/PingAddPostFragment.kt
  app/src/main/java/com/ping/app/ui/feature/map/PingMapFragment.kt
  app/src/main/java/com/ping/app/ui/util/FunctionUtil.kt
  app/src/main/java/com/ping/app/ui/util/LocationHelper.kt
  app/src/main/res/drawable/bg_add_post_dialog.xml
  app/src/main/res/layout/dialog_ping_add.xml
  app/src/main/res/layout/fragment_ping_add_post.xml
  app/src/main/res/values/strings.xml
Labels: PR

#3 Feature/#3 login UI setting
  app/src/main/java/com/ping/app/PingApplication.kt
  app/src/main/java/com/ping/app/data/repository/login/LoginRepoImpl.kt
  app/src/main/java/com/ping/app/domain/dao/LoginRepo.kt
  app/src/main/java/com/ping/app/domain/model/User.kt
  app/src/main/java/com/ping/app/ui/container/MainActivityViewModel.kt
  app/src/main/java/com/ping/app/ui/feature/login/LoginFragment.kt
  app/src/main/java/com/ping/app/ui/feature/login/LoginViewModel.kt
  app/src/main/java/com/ping/app/ui/util/Constants.kt
  app/src/main/res/layout/fragment_login.xml
Labels: PR

#6 feat: google sign in 로직 업데이트, 로그아웃 추가
  app/src/main/java/com/ping/app/data/repository/login/LoginRepoImpl.kt
  app/src/main/java/com/ping/app/domain/dao/LoginRepo.kt
  app/src/main/java/com/ping/app/ui/feature/login/LoginFragment.kt
  app/src/main/res/layout/fragment_login.xml
  build.gradle.kts
Labels: 업데이트, REFACTOR

#7 Feature/#7 fcm setting
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ping/app/data/remote/PingFirebaseMessagingService.kt
  app/src/main/java/com/ping/app/data/repository/CloudFunctionRepoImpl.kt
  app/src/main/java/com/ping/app/domain/dao/CloudFunctionRepo.kt
  app/src/main/java/com/ping/app/ui/container/MainActivity.kt
  app/src/main/java/com/ping/app/ui/util/Constants.kt
  app/src/main/res/drawable/ic_logo.png
  firebase/.gitignore
  firebase/functions/.gitignore
Labels: PR

#9 Feature/#9 credential migration
  app/build.gradle.kts
  app/src/main/java/com/ping/app/data/repository/login/LoginRepo.kt
  app/src/main/java/com/ping/app/data/repository/login/LoginRepoImpl.kt
  app/src/main/java/com/ping/app/ui/ui/container/MainActivity.kt
  app/src/main/java/com/ping/app/ui/ui/feature/login/LoginFragment.kt
  buildSrc/src/main/java/Dependencies.kt
  buildSrc/src/main/java/Versions.kt
Labels: 업데이트, PR, REFACTOR

#10 Feature/#4 main UI
  app/src/main/java/com/ping/app/PingApplication.kt
  app/src/main/java/com/ping/app/data/repository/login/LoginRepoImpl.kt
  app/src/main/java/com/ping/app/data/repository/main/MainRepo.kt
  app/src/main/java/com/ping/app/data/repository/main/MainRepoImpl.kt
  app/src/main/java/com/ping/app/ui/feature/main/MainAdapter.kt
  app/src/main/java/com/ping/app/ui/presentation/MainActivityViewModel.kt
  app/src/main/java/com/ping/app/ui/presentation/main/MainViewModel.kt
  app/src/main/java/com/ping/app/ui/ui/container/MainActivity.kt
  app/src/main/java/com/ping/app/ui/ui/feature/login/LoginFragment.kt
  app/src/main/java/com/ping/app/ui/ui/feature/main/MainFragment.kt
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_main.xml
  app/src/main/res/layout/main_item.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: PR

#11 #11 meeting table save
  app/src/main/java/com/ping/app/data/model/GatheringDetail.kt
  app/src/main/java/com/ping/app/data/repository/login/LoginRepoImpl.kt
  app/src/main/java/com/ping/app/data/repository/main/MainRepo.kt
  app/src/main/java/com/ping/app/data/repository/main/MainRepoImpl.kt
  app/src/main/java/com/ping/app/data/repository/map/PingMapRepo.kt
  app/src/main/java/com/ping/app/data/repository/map/PingMapRepoImpl.kt
  app/src/main/java/com/ping/app/ui/ui/feature/login/LoginFragment.kt
  app/src/main/java/com/ping/app/ui/ui/feature/main/MainFragment.kt
  app/src/main/java/com/ping/app/ui/ui/feature/map/PingAddPostFragment.kt
Labels: PR

#13 Feature/#10 gathering page
  app/build.gradle.kts
  app/src/main/java/com/ping/app/data/model/Gathering.kt
  app/src/main/java/com/ping/app/data/repository/gathering/GatheringRepo.kt
  app/src/main/java/com/ping/app/data/repository/gathering/GatheringRepoImpl.kt
  app/src/main/java/com/ping/app/data/repository/login/LoginRepo.kt
  app/src/main/java/com/ping/app/data/repository/login/LoginRepoImpl.kt
  app/src/main/java/com/ping/app/ui/presentation/gathering/GatheringViewModel.kt
  app/src/main/java/com/ping/app/ui/ui/container/MainActivity.kt
  app/src/main/java/com/ping/app/ui/ui/feature/gathering/GatheringFragment.kt
  app/src/main/java/com/ping/app/ui/ui/feature/main/MainAdapter.kt
  app/src/main/java/com/ping/app/ui/ui/feature/main/MainFragment.kt
  app/src/main/java/com/ping/app/ui/ui/feature/map/PingAddMapFragment.kt
  app/src/main/java/com/ping/app/ui/ui/feature/map/PingAddPostFragment.kt
  app/src/main/java/com/ping/app/ui/ui/feature/map/PingAlertDialog.kt
  app/src/main/java/com/ping/app/ui/ui/feature/map/PingMapFragment.kt
  app/src/main/java/com/ping/app/ui/ui/util/FunctionUtil.kt
  app/src/main/res/drawable/baseline_add_24.xml
  app/src/main/res/drawable/baseline_arrow_forward_ios_24.xml
  app/src/main/res/drawable/baseline_notifications_24.xml
  app/src/main/res/drawable/baseline_settings_24.xml
  app/src/main/res/drawable/bg_iv_profile.xml
  app/src/main/res/drawable/bg_white_round_10.xml
  app/src/main/res/drawable/ic_map_add.png
  app/src/main/res/layout/dialog_ping.xml
  app/src/main/res/layout/fragment_gathering.xml
  app/src/main/res/layout/fragment_main.xml
  app/src/main/res/layout/fragment_ping_map.xml
  app/src/main/res/layout/fragment_ping_map_add.xml
  app/src/main/res/layout/item_main.xml
  app/src/main/res/layout/main_item.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  build.gradle.kts
  buildSrc/src/main/java/Dependencies.kt
  buildSrc/src/main/java/Versions.kt
Labels: PR, DESIGN

#14 Feature/#14 meeting table password
  app/src/main/java/com/ping/app/data/repository/main/MainRepo.kt
  app/src/main/java/com/ping/app/data/repository/main/MainRepoImpl.kt
  app/src/main/java/com/ping/app/ui/ui/feature/main/MainFragment.kt
Labels: PR

#15 feat : 리사이클러뷰 암호화 분기 처리 와 dialog 생성 및 PingMapFragment에서 모임 참가 기능 추가
  app/src/main/java/com/ping/app/data/model/GatheringDetail.kt
  app/src/main/java/com/ping/app/data/repository/main/MainRepo.kt
  app/src/main/java/com/ping/app/data/repository/main/MainRepoImpl.kt
  app/src/main/java/com/ping/app/data/repository/map/PingMapRepo.kt
  app/src/main/java/com/ping/app/data/repository/map/PingMapRepoImpl.kt
  app/src/main/java/com/ping/app/ui/ui/feature/main/MainAdapter.kt
  app/src/main/java/com/ping/app/ui/ui/feature/main/MainAlertDialog.kt
  app/src/main/java/com/ping/app/ui/ui/feature/main/MainFragment.kt
  app/src/main/java/com/ping/app/ui/ui/feature/map/PingMapFragment.kt
  app/src/main/res/drawable/baseline_lock_24.xml
  app/src/main/res/layout/dialog_main.xml
  app/src/main/res/layout/fragment_ping_map.xml
  app/src/main/res/layout/item_main.xml
  app/src/main/res/values/strings.xml
Labels: PR

#16 Feature/#16 cloudfunction with fcm
  app/build.gradle.kts
  app/src/main/java/com/ping/app/PingApplication.kt
  app/src/main/java/com/ping/app/data/database/TestDatabase.kt
  app/src/main/java/com/ping/app/data/database/dao/TestDao.kt
  app/src/main/java/com/ping/app/data/database/entity/TestEntity.kt
  app/src/main/java/com/ping/app/data/repository/login/LoginRepo.kt
  app/src/main/java/com/ping/app/data/repository/login/LoginRepoImpl.kt
  app/src/main/java/com/ping/app/data/repository/main/MainRepoImpl.kt
  app/src/main/java/com/ping/app/data/repository/map/PingMapRepoImpl.kt
  app/src/main/java/com/ping/app/ui/presentation/MainActivityViewModel.kt
  app/src/main/java/com/ping/app/ui/presentation/main/MainViewModel.kt
  app/src/main/java/com/ping/app/ui/ui/feature/login/LoginFragment.kt
  app/src/main/java/com/ping/app/ui/ui/feature/main/MainAdapter.kt
  app/src/main/java/com/ping/app/ui/ui/feature/main/MainFragment.kt
  app/src/main/java/com/ping/app/ui/ui/feature/map/PingAddPostFragment.kt
  app/src/main/java/com/ping/app/ui/ui/feature/map/PingMapFragment.kt
  app/src/main/res/layout/fragment_main.xml
  app/src/main/res/values/strings.xml
  buildSrc/src/main/java/Dependencies.kt
  buildSrc/src/main/java/Versions.kt
  firebase-task/.firebaserc
  firebase-task/.gitignore
  firebase-task/firebase.json
  firebase-task/firestore.indexes.json
  firebase-task/firestore.rules
  firebase-task/functions/.gitignore
  firebase-task/functions/index.js
  firebase-task/functions/package-lock.json
  firebase-task/functions/package.json
Labels: 버그수정, PR, REFACTOR

#17 feat : detailMeeting participants 중복 체크
  app/src/main/java/com/ping/app/data/repository/main/MainRepo.kt
  app/src/main/java/com/ping/app/data/repository/main/MainRepoImpl.kt
  app/src/main/java/com/ping/app/ui/ui/feature/main/MainFragment.kt
Labels: PR

#18 feat : MeetingTable 중복 체크
  app/src/main/java/com/ping/app/data/repository/main/MainRepo.kt
  app/src/main/java/com/ping/app/data/repository/main/MainRepoImpl.kt
  app/src/main/java/com/ping/app/ui/ui/feature/main/MainFragment.kt
  app/src/main/res/values/strings.xml
Labels: PR

#19 Feature/#20 UI gathering event
  app/src/main/java/com/ping/app/data/repository/gathering/GatheringRepo.kt
  app/src/main/java/com/ping/app/data/repository/gathering/GatheringRepoImpl.kt
  app/src/main/java/com/ping/app/ui/presentation/gathering/GatheringViewModel.kt
  app/src/main/java/com/ping/app/ui/ui/feature/gathering/GatheringFragment.kt
  app/src/main/java/com/ping/app/ui/ui/feature/main/MainFragment.kt
  app/src/main/java/com/ping/app/ui/ui/feature/map/PingMapFragment.kt
  app/src/main/res/drawable/ic_logout.xml
  app/src/main/res/layout/fragment_gathering.xml
  app/src/main/res/layout/fragment_main.xml
  app/src/main/res/layout/fragment_ping_map.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: PR, DESIGN

#20 Feature/#21 retrofit setting
  app/build.gradle.kts
  app/src/main/java/com/ping/app/PingApplication.kt
  app/src/main/java/com/ping/app/data/model/gpt/ChatGptRequest.kt
  app/src/main/java/com/ping/app/data/model/gpt/ChatGptResponse.kt
  app/src/main/java/com/ping/app/data/model/gpt/Choice.kt
  app/src/main/java/com/ping/app/data/model/gpt/Message.kt
  app/src/main/java/com/ping/app/data/remote/ChatGPTService.kt
  app/src/main/java/com/ping/app/data/remote/NetworkModule.kt
  app/src/main/java/com/ping/app/data/repository/TestRepo.kt
  app/src/main/java/com/ping/app/data/repository/TestRepoImpl.kt
  app/src/main/java/com/ping/app/data/repository/chatgpt/ChatGPTRepo.kt
  app/src/main/java/com/ping/app/data/repository/chatgpt/ChatGPTRepoImpl.kt
  app/src/main/java/com/ping/app/data/repository/cloudfunction/CloudFunctionRepo.kt
  app/src/main/java/com/ping/app/data/repository/cloudfunction/CloudFunctionRepoImpl.kt
  app/src/main/java/com/ping/app/ui/ui/feature/main/MainFragment.kt
  buildSrc/src/main/java/Dependencies.kt
  buildSrc/src/main/java/Versions.kt
Labels: PR

#21 Feature/#17 main to detail shortcuts
  app/src/main/java/com/ping/app/data/repository/main/MainRepoImpl.kt
  app/src/main/java/com/ping/app/data/repository/map/PingMapRepo.kt
  app/src/main/java/com/ping/app/data/repository/map/PingMapRepoImpl.kt
  app/src/main/java/com/ping/app/ui/presentation/main/MainViewModel.kt
  app/src/main/java/com/ping/app/ui/ui/feature/main/MainFragment.kt
  app/src/main/java/com/ping/app/ui/ui/feature/map/PingAlertCancelDialog.kt
  app/src/main/java/com/ping/app/ui/ui/feature/map/PingMapFragment.kt
  app/src/main/res/layout/dialog_ping_cancle.xml
  app/src/main/res/layout/fragment_main.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: PR

#22 Feature/#22 splash screen
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ping/app/ui/ui/container/MainActivity.kt
  app/src/main/java/com/ping/app/ui/ui/feature/main/MainFragment.kt
  app/src/main/java/com/ping/app/ui/ui/util/LocationHelper.kt
  app/src/main/res/values/themes.xml
  app/src/test/java/com/ping/app/ExampleUnitTest.kt
  app/src/test/java/com/ping/app/GptTest.kt
  buildSrc/src/main/java/Dependencies.kt
  buildSrc/src/main/java/Versions.kt
Labels: PR

#23 Feature/#24 cleaning code
  README.md
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ping/app/PingApplication.kt
  app/src/main/java/com/ping/app/data/model/Gathering.kt
  app/src/main/java/com/ping/app/data/repository/login/LoginRepo.kt
  app/src/main/java/com/ping/app/data/repository/login/LoginRepoImpl.kt
  app/src/main/java/com/ping/app/data/repository/main/MainRepoImpl.kt
  app/src/main/java/com/ping/app/ui/base/BaseBottomSheetDialogFragment.kt
  app/src/main/java/com/ping/app/ui/base/BaseDialog.kt
  app/src/main/java/com/ping/app/ui/presentation/login/LoginViewModel.kt
  app/src/main/java/com/ping/app/ui/presentation/main/MainViewModel.kt
  app/src/main/java/com/ping/app/ui/presentation/map/PingMapViewModel.kt
  app/src/main/java/com/ping/app/ui/ui/container/MainActivity.kt
  app/src/main/java/com/ping/app/ui/ui/feature/login/LoginFragment.kt
  app/src/main/java/com/ping/app/ui/ui/feature/main/MainAdapter.kt
  app/src/main/java/com/ping/app/ui/ui/feature/main/MainAlertDialog.kt
  app/src/main/java/com/ping/app/ui/ui/feature/main/MainFragment.kt
  app/src/main/java/com/ping/app/ui/ui/feature/map/PingAddMapFragment.kt
  app/src/main/java/com/ping/app/ui/ui/feature/map/PingAddPostFragment.kt
  app/src/main/java/com/ping/app/ui/ui/feature/map/PingAlertCancelDialog.kt
  app/src/main/java/com/ping/app/ui/ui/feature/map/PingAlertDialog.kt
  app/src/main/java/com/ping/app/ui/ui/feature/map/PingMapFragment.kt
  app/src/main/java/com/ping/app/ui/ui/util/Constants.kt
  app/src/main/res/drawable/bg_white_radius_30.xml
  app/src/main/res/layout/fragment_main.xml
  app/src/main/res/layout/fragment_ping_add_post.xml
  app/src/main/res/layout/fragment_ping_map.xml
  app/src/main/res/layout/item_main.xml
  app/src/main/res/values/strings.xml
  firebase-task/functions/index.js
Labels: 버그수정, PR, DESIGN, REFACTOR

#24 feat : chatGpt api를 이용한 챗봇 기능 추가
  app/src/main/java/com/ping/app/data/model/gpt/ChatBubble.kt
  app/src/main/java/com/ping/app/data/repository/chatgpt/ChatGPTRepoImpl.kt
  app/src/main/java/com/ping/app/ui/presentation/chat/ChatViewModel.kt
  app/src/main/java/com/ping/app/ui/ui/feature/chat/ChatAdapter.kt
  app/src/main/java/com/ping/app/ui/ui/feature/chat/ChatFragment.kt
  app/src/main/java/com/ping/app/ui/ui/feature/main/MainFragment.kt
  app/src/main/java/com/ping/app/ui/ui/feature/map/PingMapFragment.kt
  app/src/main/res/drawable/baseline_chat_24.xml
  app/src/main/res/drawable/chat_gpt.9.png
  app/src/main/res/drawable/chat_me.9.png
  app/src/main/res/layout/fragment_chat.xml
  app/src/main/res/layout/fragment_main.xml
  app/src/main/res/layout/item_chat.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: PR, DESIGN

#25 Feature/#25 remove deprecated functions
  README.md
  app/build.gradle.kts
  app/src/main/java/com/ping/app/data/repository/main/MainRepo.kt
  app/src/main/java/com/ping/app/data/repository/main/MainRepoImpl.kt
  app/src/main/java/com/ping/app/data/repository/map/PingMapRepo.kt
  app/src/main/java/com/ping/app/data/repository/map/PingMapRepoImpl.kt
  app/src/main/java/com/ping/app/ui/presentation/chat/ChatViewModel.kt
  app/src/main/java/com/ping/app/ui/presentation/map/PingMapViewModel.kt
  app/src/main/java/com/ping/app/ui/ui/container/MainActivity.kt
  app/src/main/java/com/ping/app/ui/ui/feature/chat/ChatFragment.kt
  app/src/main/java/com/ping/app/ui/ui/feature/main/MainFragment.kt
  app/src/main/java/com/ping/app/ui/ui/feature/map/PingAddMapFragment.kt
  app/src/main/java/com/ping/app/ui/ui/feature/map/PingAddPostFragment.kt
  app/src/main/java/com/ping/app/ui/ui/util/MovableFloatingActionButton.kt
  app/src/main/res/drawable/bg_radius_20.xml
  app/src/main/res/drawable/ic_gpt.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_chat.xml
  app/src/main/res/layout/fragment_main.xml
  app/src/main/res/layout/fragment_ping_add_post.xml
  app/src/main/res/layout/item_chat.xml
  app/src/main/res/raw/robot.json
  buildSrc/src/main/java/Dependencies.kt
  buildSrc/src/main/java/Versions.kt
Labels: 버그수정, PR, DESIGN, REFACTOR

#26 Feature/#26 organizer short cut
  app/src/main/java/com/ping/app/data/repository/main/MainRepo.kt
  app/src/main/java/com/ping/app/data/repository/main/MainRepoImpl.kt
  app/src/main/java/com/ping/app/data/repository/map/PingMapRepoImpl.kt
  app/src/main/java/com/ping/app/ui/presentation/main/MainViewModel.kt
  app/src/main/java/com/ping/app/ui/ui/feature/main/MainFragment.kt
  app/src/main/res/layout/fragment_main.xml
  app/src/main/res/values/strings.xml
Labels: 버그수정, PR, DESIGN

#27 Feature/#27 chore fix
  app/src/main/java/com/ping/app/ui/presentation/chat/ChatViewModel.kt
  app/src/main/java/com/ping/app/ui/ui/feature/main/MainFragment.kt
  app/src/main/java/com/ping/app/ui/ui/feature/map/PingMapFragment.kt
  app/src/main/res/layout/dialog_ping.xml
  app/src/main/res/layout/dialog_ping_cancle.xml
  app/src/main/res/layout/fragment_main.xml
  app/src/main/res/layout/fragment_ping_map.xml
  app/src/main/res/values/strings.xml
Labels: 버그수정, PR, DESIGN

#28 Feature/#28 logo image update
  app/src/main/ic_launcher-playstore.png
  app/src/main/java/com/ping/app/ui/ui/util/MovableFloatingActionButton.kt
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values/ic_launcher_background.xml
Labels: DESIGN

#29 docs: README.md
  README.md
Labels: DESIGN

#30 #30 gpt hot fix
  app/src/main/java/com/ping/app/ui/presentation/chat/ChatViewModel.kt
  app/src/main/java/com/ping/app/ui/ui/container/MainActivity.kt
  app/src/main/java/com/ping/app/ui/ui/feature/chat/ChatFragment.kt
  app/src/main/res/layout/fragment_chat.xml
Labels: 버그수정, PR, REFACTOR

#31 Feature/#31 fix gpt bug
  app/src/main/java/com/ping/app/ui/presentation/chat/ChatViewModel.kt
  app/src/main/java/com/ping/app/ui/ui/feature/chat/ChatFragment.kt
  app/src/main/java/com/ping/app/ui/ui/feature/map/PingMapFragment.kt
  app/src/main/java/com/ping/app/ui/ui/util/FunctionUtil.kt
  app/src/main/res/values/strings.xml
Labels: 버그수정

#33 Update README.md
  README.md
Labels: PR
